version: "3.9"
services:
  php:
    build:
      context: .
      target: app_php
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php

  web:
    build:
      context: .
      target: app_nginx
    ports:
      - "${HTTP_PORT:-80}:80/tcp"
      - "${HTTPS_PORT:-443}:443/tcp"
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./public:/srv/app/public:ro
      - php_socket:/var/run/php

volumes:
  php_socket: