version: "3.9"
services:
  php:
    build:
      context: .
      target: app_php
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php

  web:
    build:
      context: .
      target: app_nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./public:/srv/app/public:ro
      - php_socket:/var/run/php
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
    restart: always

volumes:
  php_socket: